server:
    port: 8081
spring:
    application:
        name: cola-web
    #兼容swagger3.0
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    # 配置数据源
    datasource:
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/java-test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        type: com.alibaba.druid.pool.DruidDataSource

#mybatis 配置
mybatis-plus:
    mapper-locations:
        - classpath*:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
        log-impl: ${LOG-IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}
    global-config:
        db-config:
            id-type: AUTO
        banner: false